<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Categorie;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByCategorieQB(Categorie $categorie)
    {
    	$queryBuilder = $this->createQueryBuilder('f')
            ->where('film.categorie = :categorie')
            ->setParameter('categorie', $categorie)
            ->orderBy('film.id');

        return $queryBuilder;
    }
}
