sketch_index:
    path:     /
    defaults: { _controller: "AppBundle:Sketch:index" }
    methods:  GET

sketch_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sketch:show" }
    methods:  GET

sketch_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sketch:new" }
    methods:  [GET, POST]

sketch_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sketch:edit" }
    methods:  [GET, POST]

sketch_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sketch:delete" }
    methods:  DELETE
