front_index:
    path:     /
    methods: GET
    defaults: { _controller: "AppBundle:Front:index" }

sketch:
    resource: '@AppBundle/Resources/config/routing/sketch.yml'
    prefix:   /sketch

serie:
    resource: "@AppBundle/Resources/config/routing/serie.yml"
    prefix:   /serie