front_index:
    path:     /
    methods: GET
    defaults: { _controller: "AppBundle:Front:index" }

film:
    resource: '@AppBundle/Resources/config/routing/film.yml'
    prefix:   /film

categorie:
    resource: "@AppBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie