front_index:
    path:     /
    methods: GET
    defaults: { _controller: "AppBundle:Front:index" }

sketch:
    resource: '@AppBundle/Resources/config/routing/sketch.yml'
    prefix:   /sketch

collection:
    resource: "@AppBundle/Resources/config/routing/collection.yml"
    prefix:   /collection