AppBundle\Entity\Serie:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SerieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        sketchs:
            targetEntity: AppBundle\Entity\Sketch
            mappedBy: serie
            cascade: ["persist", "refresh"]
