AppBundle\Entity\Sketch:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SketchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        image:
            type: string
            length: 255   
    lifecycleCallbacks: {  }
