AppBundle\Entity\Sketch:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SketchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        image:
            type: string
            length: 255
        page:
            type: integer
            length: 255
            nullable: true # à changer
    lifecycleCallbacks: {  }
    manyToOne:
        collection:
            targetEntity: AppBundle\Entity\Collection
            inversedBy: sketchs
            joinColunm:
                name: collection_id
                referencedColumnName: id
